// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRg7IF0h18Ojv_Ed5O5Yz38rUlLGkB2KU',
    appId: '1:605205179267:web:f4d8f957270df2842c64b6',
    messagingSenderId: '605205179267',
    projectId: 'studentunionvotingapp-488bd',
    authDomain: 'studentunionvotingapp-488bd.firebaseapp.com',
    storageBucket: 'studentunionvotingapp-488bd.appspot.com',
    measurementId: 'G-R7GWKWY0VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiCc2xCtCioRQi3NnVm5gwKbaL7G_pmiI',
    appId: '1:605205179267:android:17ce61211345b5732c64b6',
    messagingSenderId: '605205179267',
    projectId: 'studentunionvotingapp-488bd',
    storageBucket: 'studentunionvotingapp-488bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1s-o8HCazgQxLOQkmK0xEYfcoIbEa1mc',
    appId: '1:605205179267:ios:7bc5daefc614b9362c64b6',
    messagingSenderId: '605205179267',
    projectId: 'studentunionvotingapp-488bd',
    storageBucket: 'studentunionvotingapp-488bd.appspot.com',
    iosBundleId: 'com.example.studentUnionVotingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1s-o8HCazgQxLOQkmK0xEYfcoIbEa1mc',
    appId: '1:605205179267:ios:7bc5daefc614b9362c64b6',
    messagingSenderId: '605205179267',
    projectId: 'studentunionvotingapp-488bd',
    storageBucket: 'studentunionvotingapp-488bd.appspot.com',
    iosBundleId: 'com.example.studentUnionVotingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRg7IF0h18Ojv_Ed5O5Yz38rUlLGkB2KU',
    appId: '1:605205179267:web:d8e078120d4de3242c64b6',
    messagingSenderId: '605205179267',
    projectId: 'studentunionvotingapp-488bd',
    authDomain: 'studentunionvotingapp-488bd.firebaseapp.com',
    storageBucket: 'studentunionvotingapp-488bd.appspot.com',
    measurementId: 'G-XY64YK96JP',
  );
}
